# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SweatOut' do

  pod 'FillableLoaders', '~>1.2.6'

end

target 'SweatOutTests' do

end

